backend:
  name: git-gateway
  branch: main

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "personal"
    label: "Personal Info"
    file: "data/data.json"
    fields:
      - { label: "Name", name: "personal.name", widget: "string" }
      - { label: "Title", name: "personal.title", widget: "string" }
      - { label: "Headline", name: "personal.headline", widget: "string" }
      - { label: "Subtitle", name: "personal.subtitle", widget: "text" }
      - { label: "Bio", name: "personal.bio", widget: "text" }
      - { label: "Email", name: "personal.email", widget: "string" }
      - { label: "Phone", name: "personal.phone", widget: "string" }
      - { label: "Profile Image", name: "personal.profileImage", widget: "image" }
      - { label: "Resume", name: "personal.resume", widget: "string" }

  - name: "skills"
    label: "Skills"
    file: "data/data.json"
    fields:
      - { label: "Skills", name: "skills", widget: "list", field: {label: Skill, name: skill, widget: string} }

  - name: "services"
    label: "Services"
    file: "data/data.json"
    fields:
      - label: "Services"
        name: "services"
        widget: "list"
        fields:
          - { label: "ID", name: "id", widget: "number" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
          - { label: "Icon", name: "icon", widget: "string" }
          - { label: "Features", name: "features", widget: "list", field: { label: Feature, name: feature, widget: string } }

  - name: "projects"
    label: "Projects"
    file: "data/data.json"
    fields:
      - label: "Projects"
        name: "projects"
        widget: "list"
        fields:
          - { label: "ID", name: "id", widget: "number" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
          - { label: "Image", name: "image", widget: "image" }
          - { label: "Category", name: "category", widget: "string" }
          - { label: "Technologies", name: "technologies", widget: "list" }
          - { label: "Live Link", name: "link", widget: "string" }
          - { label: "GitHub Link", name: "github", widget: "string" }

  - name: "testimonials"
    label: "Testimonials"
    file: "data/data.json"
    fields:
      - label: "Testimonials"
        name: "testimonials"
        widget: "list"
        fields:
          - { label: "ID", name: "id", widget: "number" }
          - { label: "Name", name: "name", widget: "string" }
          - { label: "Position", name: "position", widget: "string" }
          - { label: "Content", name: "content", widget: "text" }
          - { label: "Rating", name: "rating", widget: "number" }
          - { label: "Image", name: "image", widget: "image" }
